export const partnerRoutes = {
  vendor: {
    login: "/vendor",
    dashboard: "/vendor/dashboard",
    products: "/vendor/products",
    productsNew: "/vendor/products/new",
    product: (id) => `/vendor/products/${id}`,
    productEdit: (id) => `/vendor/products/${id}/edit`,
    inventory: "/vendor/inventory",
    batches: "/vendor/inventory/batches",
    orders: "/vendor/orders",
    order: (id) => `/vendor/orders/${id}`,
    prescriptionOrders: "/vendor/prescription-orders",
    prescriptionOrder: (id) => `/vendor/prescription-orders/${id}`,
    returns: "/vendor/returns",
    reports: "/vendor/sales-report",
    salesReport: "/vendor/sales-report",
    payouts: "/vendor/payouts",
    notifications: "/vendor/notifications",
    staff: "/vendor/staff",
    settings: "/vendor/account-settings",
    accountSettings: "/vendor/account-settings",
    security: "/vendor/security",
  },
};
